require('./unit-tests');
require('./docker_start');
require('./create-test-db');
require('./account-validation-tests');
require('./webhooks-tests');
require('./say-tests');
require('./gather-tests');
require('./remove-test-db');
require('./docker_stop');
